[workspace]
members = ["protocol_base", "protocol_codegen"]

[package]
name = "kafka_protocol"
version = "0.1.0"
authors = ["Diggory Blake <diggsey@googlemail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.11", features = ["tcp", "io-util", "sync", "time", "rt-core", "stream", "macros"] }
tokio-util = { version = "0.2.0", features = ["codec"] }
bytes = "0.5.4"
uuid = "0.8.1"
log = "0.4.8"
futures = "0.3.4"
async-trait = "0.1.24"
chashmap = "2.2.2"
protocol_base = { version = "0.1", path = "protocol_base" }
indexmap = "1.3.2"
env_logger = "0.7.1"
crc = "1.8.1"
snap = "1.0"
flate2 = "1.0"
string = { version = "0.2.1", git = "https://github.com/carllerche/string.git" }

[build-dependencies]
async-trait = "0.1.24"