[workspace]
members = ["protocol_codegen"]

[package]
name = "kafka-protocol"
version = "0.4.0"
authors = [
    "Diggory Blake <diggsey@googlemail.com>",
    "Jem McElwain <jmcelwain@gmail.com>",
    "belltoy <belltoy@gmail.com>",
]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Implementation of Kafka wire protocol."
homepage = "https://github.com/tychedelia/kafka-protocol-rs"
repository = "https://github.com/tychedelia/kafka-protocol-rs"
documentation = "https://docs.rs/kafka-protocol"
readme = "README.md"
keywords = ["kafka"]


[dependencies]
bytes = "1.0.1"
uuid = "0.8.2"
log = "0.4.14"
indexmap = "1.7.0"
env_logger = "0.8.4"
crc = "2.0.0"
snap = "1.0.5"
flate2 = "1.0.20"
string = "0.3.0"
derive_builder = "0.10.2"
paste = "1.0.7"
